// prettier-ignore
const translation = {
  Global: {
    EnterPin: 'Enter PIN',
    EnterNewPin: 'Enter new PIN',
    SixDigitPin: '6-digit PIN',
    Submit: 'Submit',
    Cancel: 'Cancel',
    Confirm: 'Confirm',
    Accept: 'Accept',
    Reject: 'Reject',
    Share: 'Share',
    Decline: 'Decline',
    Back: 'Back',
    Next: 'Next',
    Continue: 'Continue',
    Info: 'Information',
    Failure: 'Failure',
    Success: 'Success',
    SomethingWentWrong: 'Something went wrong',
    Done: 'Done',
    Skip: 'Skip',
    Previous: 'Previous',
    View: 'View',
    Home: 'Home',
    ErrorCode: 'Error code',
    Okay: 'OK',
    Verify: 'Verify',
    ChangePin: 'Change PIN',
    OldPin: 'Enter old PIN',
    Copy: 'Copy',
    from: 'from',
    Yes: 'Yes',
    No: 'No',
    Expire: 'Expired',
    Active: 'Active',
    Expires: 'Expires in',
    NoExpire: 'No expiration date',
    ThisDecisionCannotBeChanged: 'This decision cannot be changed.',
    ZeroRecords: 'No records available.',
    ImportWallet: 'Import wallet.',
    UserInactivity: 'Logged out due to inactivity',
    Summary:'Summary'
  },
  Language: {
    English: 'English',
    French: 'French',
    German: 'German',
    Espanol: 'Spanish',
  },
  Registration:{
    RegisterAgain: 'Please register again',
    MnemonicMsg: 'This personal recovery phrase is the only way to export your wallet and import it on a new device. Please keep it in a safe and secret place. You can also find it later under “Settings.”',
    Passphrase: 'Passphrase',
    Mnemonic: 'Mnemonic',
    SecondCounter: 'Remaining seconds',
    WalletInitialized:'Wallet successfully initialized.',
  },
  Terms: {
    AcceptTerms: 'This app is open-source software licensed under the <apachelink>Apache License Version 2.0</apachelink> and is designed to always respect the privacy and personal data of all users, as described in our <privacylink>Privacy Policy</privacylink>.',
    AcceptTermsContinue: 'Please proceed only after you have read and accepted the listed documents.',
  },
  PinCreate: {
    UserAuthenticationPin: 'PIN',
    PinMustBe6DigitsInLength: 'PIN must be 6 digits long',
    ReEnterPinMustBe6DigitsInLength: 'Insufficient PIN length',
    PinsEnteredDoNotMatch: 'Entered PINs do not match',
    PinsSuccess: 'PIN successfully created',
    PinChange: 'PIN successfully changed',
    NewPinMatchWithOld: 'The new PIN is the same as the old one',
    SixDigitPin: '6-digit PIN',
    ReenterPin: 'Re-enter PIN',
    ReenterNewPin: 'Re-enter new PIN',
    Create: 'Create',
    ValidOldPin: 'Please enter a valid old PIN',
    WalletCreated: 'Wallet successfully created',
    OR: 'or',
    PinInfo: 'This PIN will be used to unlock your wallet',
    ChangePin: 'Change PIN',
  },
  Biometric: {
    Biometric: 'Biometric',
    BiometricConfirm: 'Confirm fingerprint',
    BiometricSuccess: 'Fingerprint successfully registered',
    BiometricFailed: 'Biometric authentication failed',
    BiometricCancel: 'You cancelled the biometric prompt',
    BiometricNotSupport: 'Biometric data not supported',
    RegisterPinandBiometric: 'Register PIN and biometrics',
    BiometricInfo: 'Register your biometric data for login',
  },
  Initialization:{
    CompleteInitialization:'Complete initialization',
    InitializationInfo:"Create a new or import an existing wallet",
    ImportWalletBtn: 'Import wallet',
    InitializationBtn: 'Initialize',
  },
  Mnemonic:{
    MnemonicTitle:'Below is your recovery phrase for future security checks',
  },
  Home: {
    Welcome: 'Welcome',
    Notifications: 'Notifications',
    NoNewUpdates: 'No new notifications.',
    NoCredentials: 'No credentials in wallet.',
    SeeAll: 'See all',
    YouHave: 'You have',
    Credential: 'Credential',
    Credentials: 'Credentials',
    InYourWallet: 'in your wallet',
    CredentialCountUndefinedError:'Credential count cannot be undefined',
  },
  PinEnter: {
    IncorrectPin: 'Incorrect PIN',
  },
  Settings: {
    ChangePin: 'Change PIN',
    Version: 'Version',
    AppPreferences: 'Preferences',
    AboutApp: 'About',
    Language: 'Language',
    Logout: 'Logout',
    LogoutMsg: 'Please confirm logout',
    MnemonicMsg: 'Mnemonic cannot be empty',
    EnterMnemonic: 'Enter mnemonic',
    ValidMnemonic: 'Valid mnemonic',
    InvalidMnemonic: 'Invalid mnemonic',
    LegalAndPrivacy: 'License & Privacy',
    ExportWallet: 'Export wallet',
    ViewMnemonic: 'View mnemonic',
    RemoveDataTitle: 'Delete account',
    RemoveDataButton: 'Remove all data',
    RemoveDataMsg: 'You will remove the wallet from your phone. Added connections and credentials will be removed from the app. Do you really want to continue?',
  },
  ExportWallet:{
    WalletExportedPath: 'Wallet exported to the following path:',
  },
  ImportWallet:{
    SelectWalletFile: 'Select a wallet file',
    EmptyMnemonic: 'Personal recovery phrase cannot be empty.',
    InvalidMnemonic: 'Invalid mnemonic',
    WalletRestoreFailed:'Wallet restore failed',
    ImportError: 'Either your email or mnemonic is incorrect. Please check both carefully.',
  },
  ConnectionInvitation:{
    VerifyMessage: 'Please carefully verify the provided connection details',
    ConsentMessage: 'New connection request',
  },
  ContactDetails: {
    Created: 'Created',
    ConnectionState: 'Connection state',
    AContact: 'A contact',
    DeleteConnection: 'Delete connection',
    DeleteConnectionAlert: 'Do you really want to delete this connection?',
    DeleteConnectionSuccess: 'Connection successfully deleted',
    DeleteConnectionFailed: 'Failed to delete connection',
    ConnectionCannotDelete: 'Mediator connection cannot be deleted',
  },
  Credentials: {
    CredentialsNotFound: 'Credential not found',
  },
  CredentialDetails: {
    Id: 'Id:',
    CreatedAt: 'Created:',
    Version: 'Version',
    Issued: 'Issued',
    RemoveFromWallet: 'Remove from wallet',
    DeleteTitle: "Delete credential?",
    DeleteConfirm: "Please confirm to remove credential."
  },
  CredentialOffer: {
    ThisIsTakingLongerThanExpected: 'This is taking longer than expected. Please try again later.',
    RejectThisCredential: 'Reject this credential?',
    AcceptingCredential: 'Accepting credential',
    SuccessfullyAcceptedCredential: 'Credential successfully accepted',
    RejectingCredential:'Rejecting credential',
    SuccessfullyRejectedCredential:'Credential successfully rejected',
    CredentialNotFound: 'Credential not found',
    CredentialAccepted: 'Credential accepted',
    CredentialRejected: 'Credential rejected',
    CredentialAddedToYourWallet: 'Credential added to your wallet',
    CredentialDeclined: 'Credential declined',
    CredentialOnTheWay: 'Credential on the way',
    CredentialOffer: 'New credential',
    IsOfferingYouACredential: 'is offering you a credential',
  },
  TabStack: {
    Home: 'Home',
    Connections: 'Connections',
    Scan: 'Scan',
    Credentials: 'Wallet',
    Settings: 'App',
    Otp: '2FA',
    Presentation: 'Proofs'
  },
  Toasts:{
    Success: 'Success',
    Error: 'Error',
    Info: 'Info',
    Warning: 'Warning',
  },
  ProofRequest: {
    Title: '<b>{{connection}}</b> requests a proof:',
    OfferDelay: 'Delay',
    RejectThisProof: 'Reject this proof?',
    AcceptingProof: 'Accepting proof',
    SuccessfullyAcceptedProof: 'Proof successfully accepted',
    ProofNotFound: 'Proof not found',
    RejectingProof: 'Rejecting proof',
    ProofAccepted: 'Proof accepted',
    ProofRejected: 'Proof rejected',
    RequestedCredentialsCouldNotBeFound: 'Requested credential could not be found',
    ProofRequest: 'New proof requested',
    NotAvailableInYourWallet: 'Credential not available in your wallet',
    ProofRequestParamsError:'Proof request incorrectly configured',
    FetchProofError:'Could not fetch proof from AFJ',
  },
  Record: {
    Hide: 'Hide',
    Show: 'Show',
    HideAll: 'Hide all',
    Hidden: 'Hidden',
  },
  QRScanner:{
    PermissionToUseCamera:'Permission to use camera',
    PermissionMessage:'App requires permission to use the camera',
    ScanMessage: 'Scan to connect',
    VerifyMessage:'Only scan trusted sources and verify connection details carefully',
    NotAValidURL:'Invalid URL',
    NotBlankURL: 'Please enter a URL',
    InvalidQrCode:'Invalid QR code',
  },
  Onboarding: {
    Slide1Title: 'Credential list',
    Slide1Text: 'View the list of issued credentials',
    Slide2Title: 'Scan to connect',
    Slide2Text: 'Scan QR to connect with organizations',
    Slide3Title: 'Secure storage',
    Slide3Text: 'Store your credentials securely in your wallet',
  },
  ScreenTitles: {
    Onboarding: 'App onboarding',
    LegalAndPrivacy: 'License & Privacy',
    CreatePin: 'Create PIN',
    Biometric: 'Biometric',
    Initialization: 'Initialize wallet',
    WalletInitialized: 'Wallet initialized',
    EnterPin: 'Login',
    ListContacts: 'Connections',
    Home: 'Notifications',
    Notifications: 'Notifications',
    ChangePin: 'Change PIN',
    Credentials: 'Credentials',
    CredentialDetails: 'Credential details',
    Settings: 'App',
    CredentialOffer: 'Credential offer',
    ProofRequest: 'Proof request',
    Language: 'Language',
    ExportWallet: 'Export wallet',
    ImportWallet: 'Import wallet',
    ContactDetails: 'Connection details',
    ViewMnemonic: 'View mnemonic',
    OTPTokens: 'OTP tokens',
    PresentationList:"Proof requests"
  },
  SearchBar: {
    placeholder: 'Search'
  },
  Otp: {
    NoTokens: "No tokens registered"
  },
  PresentationList: {
    Active:"Active requests",
    Expired: "Expired requests",
    NoActive: "No active requests",
    NoActiveRequests:'No active requests.',
    NoExpiredRequests:'No expired requests',
    DeleteRecord: 'Confirm deletion',
    DeleteRecordQuestion:'Do you really want to delete this request?',
    DeleteRecordError: 'Record could not be deleted.'
  },
  Presentation: {
    LoadError:'Error loading presentation request',
    NoRecord:'Presentation request not found',
    CouldNotLoadRequest:'Could not load request',
    NoOid4VPUrlFound:'No OID4VP URL found',
    RequestEmpty:'Request empty',
    ErrorResolveRequest:'Error resolving request',
    RequestExpired:'Request expired',
    RequestError:'Presentation request is no longer valid or has been withdrawn by the requester.',
    NoPresentationDefinitionFound:'No presentation definition found in request',
    NoCredentialsFound:'No valid credentials found.',
    NoCredentials:'No proofs found',
    PresentationSendSuccessfully:'Presentation sent successfully',
    ErrorSendingCredentials:'Error sending presentation',
    ConfirmSend:'Confirm send',
    NoValidPresentationFound:'No valid presentation request found.',
    SelectedCredentials: 'Selected credentials',
    CheckPresentation:'Check presentation',
    PresentationSend:'Presentation delivered!',
    SuccessSubtitle:'Transmission successful.',
    BacktoOverview:'Back to overview'
  },
  PresentationSelection: {
    SingleSelection:'Single proof required',
    MultiSelection:'Multiple selection allowed',
    NoCredentialsFound:'No matching proofs found.',
    AutomaticallySelected:'Automatically selected',
    SelectCredentials:'Select proofs',
    SelectCredentialsHint:'Select appropriate proofs for each requirement.',
    Request:'Request'
  },
  Scan: {
    SelectImage:'Please select an image from gallery',
    ImageLoadError: 'Error loading image',
    NoQrCode: 'No QR code detected.',
    ImageSupported:'Only JPG and PNG supported',
    NoImageSelected: 'No image selected',
    EmptyQr:'No QR detected',
    ErrorProcessingOid4VPLink:'Error processing OID4VP link:'
  }
};
export default translation;
