// prettier-ignore
const translation = {
  Global: {
    EnterPin: 'Introducir PIN',
    EnterNewPin: 'Introducir nuevo PIN',
    SixDigitPin: 'PIN de 6 dígitos',
    Submit: 'Enviar',
    Cancel: 'Cancelar',
    Confirm: 'Confirmar',
    Accept: 'Aceptar',
    Reject: 'Rechazar',
    Share: 'Compartir',
    Decline: 'Declinar',
    Back: 'Atrás',
    Next: 'Siguiente',
    Continue: 'Continuar',
    Info: 'Información',
    Failure: 'Error',
    Success: 'Éxito',
    SomethingWentWrong: 'Algo salió mal',
    Done: 'Hecho',
    Skip: 'Omitir',
    Previous: 'Anterior',
    View: 'Ver',
    Home: 'Inicio',
    ErrorCode: 'Código de error',
    Okay: 'OK',
    Verify: 'Verificar',
    ChangePin: 'Cambiar PIN',
    OldPin: 'Introducir PIN antiguo',
    Copy: 'Copiar',
    from: 'de',
    Yes: 'Sí',
    No: 'No',
    Expire: 'Expirado',
    Active: 'Activo',
    Expires: 'Expira en',
    NoExpire: 'Sin fecha de expiración',
    ThisDecisionCannotBeChanged: 'Esta decisión no se puede cambiar.',
    ZeroRecords: 'No hay registros disponibles.',
    ImportWallet: 'Importar cartera.',
    UserInactivity: 'Sesión cerrada por inactividad',
    Summary:'Resumen'
  },
  Language: {
    English: 'Inglés',
    French: 'Francés',
    German: 'Alemán',
    Espanol: 'Español',
  },
  Registration:{
    RegisterAgain: 'Por favor, regístrese de nuevo',
    MnemonicMsg: 'Esta frase mnemotécnica personal es la única forma de exportar su cartera e importarla en un nuevo dispositivo. Guárdela en un lugar seguro y privado. También puede encontrarla más tarde en el menú «Configuración».',
    Passphrase: 'Frase de contraseña',
    Mnemonic: 'Frase mnemotécnica',
    SecondCounter: 'Segundos restantes',
    WalletInitialized:'Cartera inicializada con éxito.',
  },
  Terms: {
    AcceptTerms: 'Esta aplicación es un software de código abierto bajo la <apachelink>Licencia Apache Versión 2.0</apachelink> y está diseñada para respetar siempre la privacidad y los datos personales de todos los usuarios, como se describe en nuestra <privacylink>Política de privacidad</privacylink>.',
    AcceptTermsContinue: 'Por favor, continúe solo después de haber leído y aceptado los documentos indicados.',
  },
  PinCreate: {
    UserAuthenticationPin: 'PIN',
    PinMustBe6DigitsInLength: 'El PIN debe tener 6 dígitos',
    ReEnterPinMustBe6DigitsInLength: 'Longitud de PIN insuficiente',
    PinsEnteredDoNotMatch: 'Los PIN introducidos no coinciden',
    PinsSuccess: 'PIN creado con éxito',
    PinChange: 'PIN cambiado con éxito',
    NewPinMatchWithOld: 'El nuevo PIN es igual al anterior',
    SixDigitPin: 'PIN de 6 dígitos',
    ReenterPin: 'Introducir PIN de nuevo',
    ReenterNewPin: 'Introducir nuevo PIN de nuevo',
    Create: 'Crear',
    ValidOldPin: 'Por favor, introduzca un PIN antiguo válido',
    WalletCreated: 'Cartera creada con éxito',
    OR: 'o',
    PinInfo: 'Este PIN se usa para abrir su cartera',
    ChangePin: 'Cambiar PIN',
  },
  Biometric: {
    Biometric: 'Biométrico',
    BiometricConfirm: 'Confirmar huella digital',
    BiometricSuccess: 'Huella digital registrada con éxito',
    BiometricFailed: 'Fallo en la autenticación biométrica',
    BiometricCancel: 'Canceló el aviso biométrico',
    BiometricNotSupport: 'Datos biométricos no compatibles',
    RegisterPinandBiometric: 'Registrar PIN y biometría',
    BiometricInfo: 'Registre sus datos biométricos para iniciar sesión',
  },
  Initialization:{
    CompleteInitialization:'Completar la inicialización',
    InitializationInfo:"Cree una nueva cartera o importe una existente",
    ImportWalletBtn: 'Importar cartera',
    InitializationBtn: 'Inicializar',
  },
  Mnemonic:{
    MnemonicTitle:'A continuación se muestra su frase mnemotécnica para futuras comprobaciones de seguridad',
  },
  Home: {
    Welcome: 'Bienvenido',
    Notifications: 'Notificaciones',
    NoNewUpdates: 'No hay nuevas notificaciones.',
    NoCredentials: 'No hay credenciales en la cartera.',
    SeeAll: 'Ver todo',
    YouHave: 'Tienes',
    Credential: 'Credencial',
    Credentials: 'Credenciales',
    InYourWallet: 'en tu cartera',
    CredentialCountUndefinedError:'El número de credenciales no puede ser indefinido',
  },
  PinEnter: {
    IncorrectPin: 'PIN incorrecto',
  },
  Settings: {
    ChangePin: 'Cambiar PIN',
    Version: 'Versión',
    AppPreferences: 'Preferencias',
    AboutApp: 'Acerca de',
    Language: 'Idioma',
    Logout: 'Cerrar sesión',
    LogoutMsg: 'Confirme el cierre de sesión',
    MnemonicMsg: 'La frase mnemotécnica no puede estar vacía',
    EnterMnemonic: 'Introducir frase mnemotécnica',
    ValidMnemonic: 'Frase mnemotécnica válida',
    InvalidMnemonic: 'Frase mnemotécnica no válida',
    LegalAndPrivacy: 'Licencia y privacidad',
    ExportWallet: 'Exportar cartera',
    ViewMnemonic: 'Ver frase mnemotécnica',
    RemoveDataTitle: 'Eliminar cuenta',
    RemoveDataButton: 'Eliminar todos los datos',
    RemoveDataMsg: 'Eliminará la cartera de su teléfono. Las conexiones e identificaciones añadidas se eliminarán de la aplicación. ¿Desea continuar?',
  },
  ExportWallet:{
    WalletExportedPath: 'La cartera se ha exportado a la siguiente ruta:',
  },
  ImportWallet:{
    SelectWalletFile: 'Seleccione un archivo de cartera',
    EmptyMnemonic: 'La frase mnemotécnica no puede estar vacía.',
    InvalidMnemonic: 'Frase mnemotécnica incorrecta',
    WalletRestoreFailed:'Error al restaurar la cartera',
    ImportError: 'Su correo electrónico o frase mnemotécnica es incorrecta. Revise ambos cuidadosamente.',
  },
  ConnectionInvitation:{
    VerifyMessage: 'Verifique cuidadosamente los detalles de conexión proporcionados',
    ConsentMessage: 'Nueva solicitud de conexión',
  },
  ContactDetails: {
    Created: 'Creado',
    ConnectionState: 'Estado de conexión',
    AContact: 'Un contacto',
    DeleteConnection: 'Eliminar conexión',
    DeleteConnectionAlert: '¿Desea eliminar esta conexión?',
    DeleteConnectionSuccess: 'Conexión eliminada con éxito',
    DeleteConnectionFailed: 'Error al eliminar la conexión',
    ConnectionCannotDelete: 'No se puede eliminar la conexión del mediador',
  },
  Credentials: {
    CredentialsNotFound: 'Credencial no encontrada',
  },
  CredentialDetails: {
    Id: 'Id:',
    CreatedAt: 'Creado:',
    Version: 'Versión',
    Issued: 'Emitido',
    RemoveFromWallet: 'Eliminar de la cartera',
    DeleteTitle: "¿Eliminar credencial?",
    DeleteConfirm: "Por favor, confirme para eliminar la credencial."
  },
  CredentialOffer: {
    ThisIsTakingLongerThanExpected: 'Esto está tardando más de lo esperado. Intente de nuevo más tarde.',
    RejectThisCredential: '¿Rechazar esta credencial?',
    AcceptingCredential: 'Aceptando credencial',
    SuccessfullyAcceptedCredential: 'Credencial aceptada con éxito',
    RejectingCredential:'Rechazando credencial',
    SuccessfullyRejectedCredential:'Credencial rechazada con éxito',
    CredentialNotFound: 'Credencial no encontrada',
    CredentialAccepted: 'Credencial aceptada',
    CredentialRejected: 'Credencial rechazada',
    CredentialAddedToYourWallet: 'Credencial añadida a su cartera',
    CredentialDeclined: 'Credencial declinada',
    CredentialOnTheWay: 'Credencial en camino',
    CredentialOffer: 'Nueva credencial',
    IsOfferingYouACredential: 'le ofrece una credencial',
  },
  TabStack: {
    Home: 'Inicio',
    Connections: 'Conexiones',
    Scan: 'Escanear',
    Credentials: 'Cartera',
    Settings: 'Aplicación',
    Otp: '2FA',
    Presentation: 'Pruebas'
  },
  Toasts:{
    Success: 'Éxito',
    Error: 'Error',
    Info: 'Información',
    Warning: 'Advertencia',
  },
  ProofRequest: {
    Title: '<b>{{connection}}</b> solicita una prueba:',
    OfferDelay: 'Retraso',
    RejectThisProof: '¿Rechazar esta prueba?',
    AcceptingProof: 'Aceptando prueba',
    SuccessfullyAcceptedProof: 'Prueba aceptada con éxito',
    ProofNotFound: 'Prueba no encontrada',
    RejectingProof: 'Rechazando prueba',
    ProofAccepted: 'Prueba aceptada',
    ProofRejected: 'Prueba rechazada',
    RequestedCredentialsCouldNotBeFound: 'No se pudo encontrar la credencial solicitada',
    ProofRequest: 'Nueva solicitud de prueba',
    NotAvailableInYourWallet: 'Credencial no disponible en la cartera',
    ProofRequestParamsError:'Solicitud de prueba mal configurada',
    FetchProofError:'No se pudo obtener la prueba desde AFJ',
  },
  Record: {
    Hide: 'Ocultar',
    Show: 'Mostrar',
    HideAll: 'Ocultar todo',
    Hidden: 'Oculto',
  },
  QRScanner:{
    PermissionToUseCamera:'Permiso para usar la cámara',
    PermissionMessage:'La aplicación necesita permiso para usar la cámara',
    ScanMessage: 'Escanear para conectar',
    VerifyMessage:'Escanee solo fuentes confiables y verifique cuidadosamente los detalles de conexión',
    NotAValidURL:'URL no válida',
    NotBlankURL: 'Por favor, introduzca una URL',
    InvalidQrCode:'Código QR no válido',
  },
  Onboarding: {
    Slide1Title: 'Lista de credenciales',
    Slide1Text: 'Ver la lista de credenciales emitidas',
    Slide2Title: 'Escanear para conectar',
    Slide2Text: 'Escanee un código QR para conectarse con organizaciones',
    Slide3Title: 'Almacenamiento seguro',
    Slide3Text: 'Guarde sus credenciales de forma segura en la cartera',
  },
  ScreenTitles: {
    Onboarding: 'Introducción a la aplicación',
    LegalAndPrivacy: 'Licencia y privacidad',
    CreatePin: 'Crear PIN',
    Biometric: 'Biométrico',
    Initialization: 'Inicializar cartera',
    WalletInitialized: 'Cartera inicializada',
    EnterPin: 'Inicio de sesión',
    ListContacts: 'Conexiones',
    Home: 'Notificaciones',
    Notifications: 'Notificaciones',
    ChangePin: 'Cambiar PIN',
    Credentials: 'Credenciales',
    CredentialDetails: 'Detalles de credencial',
    Settings: 'Aplicación',
    CredentialOffer: 'Oferta de credencial',
    ProofRequest: 'Solicitud de prueba',
    Language: 'Idioma',
    ExportWallet: 'Exportar cartera',
    ImportWallet: 'Importar cartera',
    ContactDetails: 'Detalles de conexión',
    ViewMnemonic: 'Ver frase mnemotécnica',
    OTPTokens: 'Tokens OTP',
    PresentationList:"Solicitudes de prueba"
  },
  SearchBar: {
    placeholder: 'Buscar'
  },
  Otp: {
    NoTokens: "No hay tokens registrados"
  },
  PresentationList: {
    Active:"Solicitudes activas",
    Expired: "Solicitudes expiradas",
    NoActive: "No hay solicitudes activas",
    NoActiveRequests:'No hay solicitudes activas.',
    NoExpiredRequests:'No hay solicitudes expiradas',
    DeleteRecord: 'Confirmar eliminación',
    DeleteRecordQuestion:'¿Desea eliminar esta solicitud?',
    DeleteRecordError: 'No se pudo eliminar el registro.'
  },
  Presentation: {
    LoadError:'Error al cargar la solicitud de presentación',
    NoRecord:'Solicitud de presentación no encontrada',
    CouldNotLoadRequest:'No se pudo cargar la solicitud',
    NoOid4VPUrlFound:'No se encontró URL OID4VP',
    RequestEmpty:'Solicitud vacía',
    ErrorResolveRequest:'Error al resolver la solicitud',
    RequestExpired:'Solicitud expirada',
    RequestError:'La solicitud de presentación ya no es válida o ha sido retirada por el solicitante.',
    NoPresentationDefinitionFound:'No se encontró definición de presentación en la solicitud',
    NoCredentialsFound:'No se encontraron credenciales válidas.',
    NoCredentials:'No se encontraron pruebas',
    PresentationSendSuccessfully:'Presentación enviada con éxito',
    ErrorSendingCredentials:'Error al enviar la presentación',
    ConfirmSend:'Confirmar envío',
    NoValidPresentationFound:'No se encontró solicitud de presentación válida.',
    SelectedCredentials: 'Credenciales seleccionadas',
    CheckPresentation:'Verificar presentación',
    PresentationSend:'¡Presentación enviada!',
    SuccessSubtitle:'Transmisión exitosa.',
    BacktoOverview:'Volver al resumen'
  },
  PresentationSelection: {
    SingleSelection:'Se requiere una sola prueba',
    MultiSelection:'Selección múltiple permitida',
    NoCredentialsFound:'No se encontraron pruebas coincidentes.',
    AutomaticallySelected:'Seleccionado automáticamente',
    SelectCredentials:'Seleccionar pruebas',
    SelectCredentialsHint:'Seleccione las pruebas adecuadas para cada requisito.',
    Request:'Solicitud'
  },
  Scan: {
    SelectImage:'Seleccione una imagen de la galería',
    ImageLoadError: 'Error al cargar la imagen',
    NoQrCode: 'No se detectó código QR.',
    ImageSupported:'Solo se admiten JPG y PNG',
    NoImageSelected: 'No se seleccionó ninguna imagen',
    EmptyQr:'No se detectó QR',
    ErrorProcessingOid4VPLink:'Error al procesar el enlace OID4VP:'
  }
};
export default translation;
