require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PersonalCredentialManager' do
   config = use_native_modules!
   use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,   # Hermes aktiv
    :fabric_enabled => false,  # nur falls du kein Fabric benutzt
    :app_path => File.join(__dir__, "..")  # -> ios/..
  )


  # Debug-Tools optional:
  # use_flipper!

  post_install do |installer|
    react_native_post_install(
      installer,
      __dir__ + '/../../node_modules/react-native',
      :mac_catalyst_enabled => false
    )

      # Fix: Codegen Pfad für FBReactNativeSpec
    installer.pods_project.targets.each do |target|
      target.shell_script_build_phases.each do |phase|
        if phase.name.include?("Check FBReactNativeSpec") || phase.name.include?("Generate Specs")
          phase.shell_script = <<-SCRIPT
            set -e
            export REACT_NATIVE_PATH="$SRCROOT/../../node_modules/react-native"
            echo "Using REACT_NATIVE_PATH=$REACT_NATIVE_PATH"

            # Richtigen Codegen-Call für RN 0.71+
            /opt/homebrew/bin/node "$REACT_NATIVE_PATH/scripts/generate-codegen-artifacts.js" \
              --path "$SRCROOT/../.." \
              --outputPath "ios" \
              --targetPlatform ios
          SCRIPT
        end
      end
    end

    #Fix: Hermes Skript-Pfad überschreiben
    installer.pods_project.targets.each do |target|
      target.shell_script_build_phases.each do |phase|
        if phase.name.include?('Hermes')
         phase.shell_script = <<-SCRIPT
            set -e
            WITH_ENVIRONMENT="$SRCROOT/../../node_modules/react-native/scripts/xcode/with-environment.sh"
            REACT_NATIVE_XCODE="$SRCROOT/../../node_modules/react-native/scripts/react-native-xcode.sh"
            "$WITH_ENVIRONMENT" "$REACT_NATIVE_XCODE"
          SCRIPT
        end
      end
    end

    installer.pods_project.targets.each do |project|
      project.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      end
    end
  end
end
