// prettier-ignore
const translation = {
  Global: {
    EnterPin: 'Entrer le code PIN',
    EnterNewPin: 'Entrer un nouveau code PIN',
    SixDigitPin: 'Code PIN à 6 chiffres',
    Submit: 'Envoyer',
    Cancel: 'Annuler',
    Confirm: 'Confirmer',
    Accept: 'Accepter',
    Reject: 'Rejeter',
    Share: 'Partager',
    Decline: 'Refuser',
    Back: 'Retour',
    Next: 'Suivant',
    Continue: 'Continuer',
    Info: 'Information',
    Failure: 'Échec',
    Success: 'Succès',
    SomethingWentWrong: 'Une erreur est survenue',
    Done: 'Terminé',
    Skip: 'Passer',
    Previous: 'Précédent',
    View: 'Voir',
    Home: 'Accueil',
    ErrorCode: 'Code d’erreur',
    Okay: 'OK',
    Verify: 'Vérifier',
    ChangePin: 'Modifier le code PIN',
    OldPin: 'Entrer l’ancien code PIN',
    Copy: 'Copier',
    from: 'de',
    Yes: 'Oui',
    No: 'Non',
    Expire: 'Expiré',
    Active: 'Actif',
    Expires: 'Expire dans',
    NoExpire: 'Aucune date d’expiration',
    ThisDecisionCannotBeChanged: 'Cette décision ne peut pas être modifiée.',
    ZeroRecords: 'Aucun enregistrement disponible.',
    ImportWallet: 'Importer le portefeuille.',
    UserInactivity: 'Déconnecté pour cause d’inactivité',
    Summary:'Résumé'
  },
  Language: {
    English: 'Anglais',
    French: 'Français',
    German: 'Allemand',
    Espanol: 'Espagnol',
  },
  Registration:{
    RegisterAgain: 'Veuillez vous enregistrer à nouveau',
    MnemonicMsg: 'Cette phrase de récupération personnelle est le seul moyen d’exporter votre portefeuille et de l’importer sur un nouvel appareil. Veuillez la conserver dans un endroit sûr et secret. Vous pouvez également la retrouver plus tard dans le menu « Paramètres ».',
    Passphrase: 'Phrase secrète',
    Mnemonic: 'Phrase mnémonique',
    SecondCounter: 'Secondes restantes',
    WalletInitialized:'Portefeuille initialisé avec succès.',
  },
  Terms: {
    AcceptTerms: 'Cette application est un logiciel open source sous licence <apachelink>Apache License Version 2.0</apachelink> et vise à respecter en tout temps la vie privée et les données personnelles de tous les utilisateurs, comme détaillé dans notre <privacylink>Politique de confidentialité</privacylink>.',
    AcceptTermsContinue: 'Veuillez continuer uniquement après avoir lu et accepté les documents indiqués.',
  },
  PinCreate: {
    UserAuthenticationPin: 'Code PIN',
    PinMustBe6DigitsInLength: 'Le code PIN doit comporter 6 chiffres',
    ReEnterPinMustBe6DigitsInLength: 'Longueur du code PIN insuffisante',
    PinsEnteredDoNotMatch: 'Les codes PIN saisis ne correspondent pas',
    PinsSuccess: 'Code PIN créé avec succès',
    PinChange: 'Code PIN modifié avec succès',
    NewPinMatchWithOld: 'Le nouveau code PIN est identique à l’ancien',
    SixDigitPin: 'Code PIN à 6 chiffres',
    ReenterPin: 'Saisir à nouveau le code PIN',
    ReenterNewPin: 'Saisir à nouveau le nouveau code PIN',
    Create: 'Créer',
    ValidOldPin: 'Veuillez entrer un ancien code PIN valide',
    WalletCreated: 'Portefeuille créé avec succès',
    OR: 'ou',
    PinInfo: 'Ce code PIN est utilisé pour ouvrir votre portefeuille',
    ChangePin: 'Modifier le code PIN',
  },
  Biometric: {
    Biometric: 'Biométrique',
    BiometricConfirm: 'Confirmer l’empreinte digitale',
    BiometricSuccess: 'Empreinte digitale enregistrée avec succès',
    BiometricFailed: 'Échec de l’authentification biométrique',
    BiometricCancel: 'Vous avez annulé la demande biométrique',
    BiometricNotSupport: 'Les données biométriques ne sont pas prises en charge',
    RegisterPinandBiometric: 'Enregistrer le code PIN et la biométrie',
    BiometricInfo: 'Enregistrez vos données biométriques pour la connexion',
  },
  Initialization:{
    CompleteInitialization:'Terminez l’initialisation',
    InitializationInfo:"Créez un nouveau portefeuille ou importez-en un existant",
    ImportWalletBtn: 'Importer le portefeuille',
    InitializationBtn: 'Initialisation',
  },
  Mnemonic:{
    MnemonicTitle:'Voici votre phrase mnémonique pour les vérifications futures de sécurité',
  },
  Home: {
    Welcome: 'Bienvenue',
    Notifications: 'Notifications',
    NoNewUpdates: 'Aucune nouvelle notification.',
    NoCredentials: 'Aucun identifiant dans le portefeuille.',
    SeeAll: 'Tout voir',
    YouHave: 'Vous avez',
    Credential: 'Identifiant',
    Credentials: 'Identifiants',
    InYourWallet: 'dans votre portefeuille',
    CredentialCountUndefinedError:'Le nombre d’identifiants ne peut pas être indéfini',
  },
  PinEnter: {
    IncorrectPin: 'Code PIN incorrect',
  },
  Settings: {
    ChangePin: 'Modifier le code PIN',
    Version: 'Version',
    AppPreferences: 'Préférences',
    AboutApp: 'À propos',
    Language: 'Langue',
    Logout: 'Déconnexion',
    LogoutMsg: 'Veuillez confirmer la déconnexion',
    MnemonicMsg: 'La phrase mnémonique ne peut pas être vide',
    EnterMnemonic: 'Entrer la phrase mnémonique',
    ValidMnemonic: 'Phrase mnémonique valide',
    InvalidMnemonic: 'Phrase mnémonique invalide',
    LegalAndPrivacy: 'Licence et confidentialité',
    ExportWallet: 'Exporter le portefeuille',
    ViewMnemonic: 'Voir la phrase mnémonique',
    RemoveDataTitle: 'Supprimer le compte',
    RemoveDataButton: 'Supprimer toutes les données',
    RemoveDataMsg: 'Vous allez supprimer le portefeuille de votre téléphone. Les connexions et identifiants ajoutés seront supprimés de l’application. Voulez-vous vraiment continuer ?',
  },
  ExportWallet:{
    WalletExportedPath: 'Le portefeuille a été exporté vers le chemin suivant :',
  },
  ImportWallet:{
    SelectWalletFile: 'Sélectionnez un fichier de portefeuille',
    EmptyMnemonic: 'La phrase de récupération personnelle ne peut pas être vide.',
    InvalidMnemonic: 'Phrase mnémonique incorrecte',
    WalletRestoreFailed:'Échec de la restauration du portefeuille',
    ImportError: 'Votre e-mail ou votre phrase mnémonique est incorrect. Veuillez vérifier attentivement les deux.',
  },
  ConnectionInvitation:{
    VerifyMessage: 'Veuillez vérifier attentivement les détails de la connexion fournie',
    ConsentMessage: 'Nouvelle demande de connexion',
  },
  ContactDetails: {
    Created: 'Créé',
    ConnectionState: 'État de la connexion',
    AContact: 'Un contact',
    DeleteConnection: 'Supprimer la connexion',
    DeleteConnectionAlert: 'Voulez-vous vraiment supprimer cette connexion ?',
    DeleteConnectionSuccess: 'Connexion supprimée avec succès',
    DeleteConnectionFailed: 'Échec de la suppression de la connexion',
    ConnectionCannotDelete: 'La connexion médiateur ne peut pas être supprimée',
  },
  Credentials: {
    CredentialsNotFound: 'Identifiant non trouvé',
  },
  CredentialDetails: {
    Id: 'Id :',
    CreatedAt: 'Créé :',
    Version: 'Version',
    Issued: 'Délivré',
    RemoveFromWallet: 'Supprimer du portefeuille',
    DeleteTitle: "Supprimer l’identifiant ?",
    DeleteConfirm: "Veuillez confirmer la suppression de l’identifiant."
  },
  CredentialOffer: {
    ThisIsTakingLongerThanExpected: 'Cela prend plus de temps que prévu. Veuillez réessayer plus tard.',
    RejectThisCredential: 'Refuser cet identifiant ?',
    AcceptingCredential: 'Acceptation de l’identifiant',
    SuccessfullyAcceptedCredential: 'Identifiant accepté avec succès',
    RejectingCredential:'Refus de l’identifiant',
    SuccessfullyRejectedCredential:'Identifiant refusé avec succès',
    CredentialNotFound: 'Identifiant non trouvé',
    CredentialAccepted: 'Identifiant accepté',
    CredentialRejected: 'Identifiant rejeté',
    CredentialAddedToYourWallet: 'Identifiant ajouté à votre portefeuille',
    CredentialDeclined: 'Identifiant refusé',
    CredentialOnTheWay: 'Identifiant en cours de traitement',
    CredentialOffer: 'Nouvel identifiant',
    IsOfferingYouACredential: 'vous propose un identifiant',
  },
  TabStack: {
    Home: 'Accueil',
    Connections: 'Connexions',
    Scan: 'Scanner',
    Credentials: 'Portefeuille',
    Settings: 'Application',
    Otp: '2FA',
    Presentation: 'Preuves'
  },
  Toasts:{
    Success: 'Succès',
    Error: 'Erreur',
    Info: 'Information',
    Warning: 'Avertissement',
  },
  ProofRequest: {
    Title: '<b>{{connection}}</b> vous demande une preuve :',
    OfferDelay: 'Délai',
    RejectThisProof: 'Refuser cette preuve ?',
    AcceptingProof: 'Acceptation de la preuve',
    SuccessfullyAcceptedProof: 'Preuve acceptée avec succès',
    ProofNotFound: 'Preuve non trouvée',
    RejectingProof: 'Refus de la preuve',
    ProofAccepted: 'Preuve acceptée',
    ProofRejected: 'Preuve rejetée',
    RequestedCredentialsCouldNotBeFound: 'Identifiant demandé introuvable',
    ProofRequest: 'Nouvelle demande de preuve',
    NotAvailableInYourWallet: 'Identifiant non disponible dans le portefeuille',
    ProofRequestParamsError:'Demande de preuve mal configurée',
    FetchProofError:'Impossible de récupérer la preuve depuis AFJ',
  },
  Record: {
    Hide: 'Masquer',
    Show: 'Afficher',
    HideAll: 'Tout masquer',
    Hidden: 'Masqué',
  },
  QRScanner:{
    PermissionToUseCamera:'Permission d’utiliser la caméra',
    PermissionMessage:'L’application nécessite la permission d’utiliser la caméra',
    ScanMessage: 'Scanner pour se connecter',
    VerifyMessage:'Scannez uniquement des sources fiables et vérifiez attentivement les détails de la connexion',
    NotAValidURL:'URL non valide',
    NotBlankURL: 'Veuillez entrer une URL',
    InvalidQrCode:'Code QR invalide',
  },
  Onboarding: {
    Slide1Title: 'Liste des identifiants',
    Slide1Text: 'Consultez la liste des identifiants émis',
    Slide2Title: 'Scanner pour se connecter',
    Slide2Text: 'Scannez un QR pour vous connecter à des organisations',
    Slide3Title: 'Stockage sécurisé',
    Slide3Text: 'Stockez vos identifiants en toute sécurité dans votre portefeuille',
  },
  ScreenTitles: {
    Onboarding: 'Introduction à l’application',
    LegalAndPrivacy: 'Licence et confidentialité',
    CreatePin: 'Création du code PIN',
    Biometric: 'Biométrique',
    Initialization: 'Initialiser le portefeuille',
    WalletInitialized: 'Portefeuille initialisé',
    EnterPin: 'Connexion',
    ListContacts: 'Connexions',
    Home: 'Notifications',
    Notifications: 'Notifications',
    ChangePin: 'Modifier le code PIN',
    Credentials: 'Identifiants',
    CredentialDetails: 'Détails de l’identifiant',
    Settings: 'Application',
    CredentialOffer: 'Offre d’identifiant',
    ProofRequest: 'Demande de preuve',
    Language: 'Langue',
    ExportWallet: 'Exporter le portefeuille',
    ImportWallet: 'Importer le portefeuille',
    ContactDetails: 'Détails de la connexion',
    ViewMnemonic: 'Voir la phrase mnémonique',
    OTPTokens: 'Jetons OTP',
    PresentationList:"Demandes de preuve"
  },
  SearchBar: {
    placeholder: 'Rechercher'
  },
  Otp: {
    NoTokens: "Aucun jeton enregistré"
  },
  PresentationList: {
    Active:"Demandes actives",
    Expired: "Demandes expirées",
    NoActive: "Aucune demande active",
    NoActiveRequests:'Aucune demande active.',
    NoExpiredRequests:'Aucune demande expirée',
    DeleteRecord: 'Confirmer la suppression',
    DeleteRecordQuestion:'Voulez-vous vraiment supprimer cette demande ?',
    DeleteRecordError: 'L’enregistrement n’a pas pu être supprimé.'
  },
  Presentation: {
    LoadError:'Erreur lors du chargement de la demande de présentation',
    NoRecord:'Demande de présentation non trouvée',
    CouldNotLoadRequest:'Impossible de charger la demande',
    NoOid4VPUrlFound:'Aucune URL OID4VP trouvée',
    RequestEmpty:'Demande vide',
    ErrorResolveRequest:'Erreur lors de la résolution de la demande',
    RequestExpired:'Demande expirée',
    RequestError:'La demande de présentation n’est plus valide ou a été retirée par le demandeur.',
    NoPresentationDefinitionFound:'Aucune définition de présentation trouvée dans la demande',
    NoCredentialsFound:'Aucun identifiant valide trouvé.',
    NoCredentials:'Aucune preuve trouvée',
    PresentationSendSuccessfully:'Présentation envoyée avec succès',
    ErrorSendingCredentials:'Erreur lors de l’envoi de la présentation',
    ConfirmSend:'Confirmer l’envoi',
    NoValidPresentationFound:'Aucune demande de présentation valide trouvée.',
    SelectedCredentials: 'Identifiants sélectionnés',
    CheckPresentation:'Vérifier la présentation',
    PresentationSend:'Présentation transmise !',
    SuccessSubtitle:'Transmission réussie.',
    BacktoOverview:'Retour à la vue d’ensemble'
  },
  PresentationSelection: {
    SingleSelection:'Preuve unique requise',
    MultiSelection:'Sélection multiple autorisée',
    NoCredentialsFound:'Aucune preuve correspondante trouvée.',
    AutomaticallySelected:'Sélectionné automatiquement',
    SelectCredentials:'Sélectionner les preuves',
    SelectCredentialsHint:'Sélectionnez les preuves appropriées pour chaque exigence.',
    Request:'Demande'
  },
  Scan: {
    SelectImage:'Veuillez sélectionner une image dans la galerie',
    ImageLoadError: 'Erreur lors du chargement de l’image',
    NoQrCode: 'Aucun code QR détecté.',
    ImageSupported:'Seuls les fichiers JPG et PNG sont pris en charge',
    NoImageSelected: 'Aucune image sélectionnée',
    EmptyQr:'Aucun QR détecté',
    ErrorProcessingOid4VPLink:'Erreur lors du traitement du lien OID4VP :'
  }
};
export default translation;
